version: '3'

services:
  voice-chatbot:
    image: ${DOCKER_HUB_USERNAME:-yourusername}/voice-chatbot:latest
    restart: unless-stopped
    expose:
      - "3011"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=production
      - PORT=3011
      - VITE_HOST=0.0.0.0
      - VITE_ALLOWED_HOST=${DOMAIN:-your-domain.com}
      - VIRTUAL_HOST=${DOMAIN:-your-domain.com}
      - VIRTUAL_PORT=3011
      - LETSENCRYPT_HOST=${DOMAIN:-your-domain.com}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-your-email@example.com}
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:3011/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - nginx-proxy-network

networks:
  nginx-proxy-network:
    external: true